# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"3\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x14\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x05.Date\"$\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x18\n\x06UserId\x12\x0e\n\x06userid\x18\x01 \x01(\t\"?\n\x0e\x42ookingPayload\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t2j\n\x07\x42ooking\x12*\n\x0fGetUserBookings\x12\x07.UserId\x1a\x0c.BookingData\"\x00\x12\x33\n\x10\x41\x64\x64\x42ookingByUser\x12\x0f.BookingPayload\x1a\x0c.BookingData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BOOKINGDATA']._serialized_start=17
  _globals['_BOOKINGDATA']._serialized_end=68
  _globals['_DATE']._serialized_start=70
  _globals['_DATE']._serialized_end=106
  _globals['_USERID']._serialized_start=108
  _globals['_USERID']._serialized_end=132
  _globals['_BOOKINGPAYLOAD']._serialized_start=134
  _globals['_BOOKINGPAYLOAD']._serialized_end=197
  _globals['_BOOKING']._serialized_start=199
  _globals['_BOOKING']._serialized_end=305
# @@protoc_insertion_point(module_scope)
